#!/bin/sh
ntpd -n -q -p 162.159.200.123
ntpd -n -q -p 122.117.253.246
LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
ping -c 1 www.baidu.com > /dev/null
ret=$?
if [ $ret -eq 0 ]
then
sed -i -e '4d' /etc/crontabs/root
/etc/init.d/cron restart
sh /root/ledoff
sh /root/line
sh /root/checkcron2
sh /root/checkcron
else
echo "[$LOGTIME] do nothing...."
sh /root/ledon
fi
