#!/bin/sh
LINE=/etc/crontabs/root
if cat $LINE | grep -q https; then
echo do nothing
#cp -f /etc/xfileu/xfile/* /etc/xfile/
elif cat $LINE | grep -q ss_watchdog2; then
echo do nothing too
#cp -f /etc/xfilem/xfile/* /etc/xfile/
else
echo use crone!
cp /dev/null /etc/crontabs/root && cat /etc/crone >> /etc/crontabs/root
/etc/init.d/cron restar
