#!/bin/sh
LINE=/etc/crontabs/root
if cat $LINE | grep -q https; then
echo do nothing
elif cat $LINE | grep -q ss_watchdog2; then
echo do nothing too
else
echo use crone!
cp /dev/null /etc/crontabs/root && cat /etc/crone >> /etc/crontabs/root
/etc/init.d/cron restart
fi
